project:
  type: website

website:
  title: "AI vs. Non-AI Job Growth"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: findings.qmd
        text: Findings
      - href: career_strategy.qmd
        text: Career Strategy
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true
    code-fold: true
    code-tools: true
    df-print: paged

execute:
  echo: false
  eval: true
  freeze: auto

bibliography: references.bib
csl: csl/econometrica.csl
jupyter: python3
